name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ "11", "17", "21" ]
        distribution: [ "zulu", "adopt" ]
        okhttp: [ "okhttp5", "okhttp4" ]
        include:
          - okhttp: "okhttp5"
            maven_profiles: ""
          - okhttp: "okhttp4"
            maven_profiles: "-P test-okhttp4"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK (${{ matrix.java }} ${{ matrix.distribution }})
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}

      - name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ matrix.okhttp }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven (OkHttp ${{ matrix.okhttp }})
        run: mvn clean install ${{ matrix.maven_profiles }}
